version: 2
updates:
  
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 3
    groups:
      dotnet:
        patterns:
          - "*"